### ISSUE TITLE
kit flow/script deployment rules: backfill and backdate

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#708] opened 2023-05-08 16:15 UTC
## Who was the customer who requested this feature?

We have some scripts/flows in gravwell kit that are generating aggs, but when you install it can't backdate the aggs, so it would be useful to be able to enable backfill and also backdate runs.

That way on first install the gravwell kit could create aggs for the last XYZ hours or days immediately.

## What is the feature to be added?

Add `BackfillEnabled` and `BackdateLastRun` values on the deploy scripts datatype

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

Makes aggs more useful

## How does this feature address the above problem?

allows aggs to be backdated/generated at install

## Any other comments?

Make sure these do NOT write on update

**Comment by john-floren-gravwell** [comment] 2023-06-14 19:00
It's easy to add the requested fields BackfillEnabled (bool) and BackdateLastRun (time.Time?) to the types.ScriptDeployConfig structure. At kit install time, check these for each automation and set the fields as requested.

The problem is updating. "Updating" a kit consists of deleting the existing kit and installing the new one. We could save the existing backfill/lastrun fields from existing automations, but what do we do about new ones? We need some way to prompt the user to set that shit only for completely new automations.

**Comment by kris-watts-gravwell** [comment] 2023-06-14 19:04
i think this can be a multi-step process:

1. Allow for setting these in the kit deployment process (can be outside the kit config)
2. Figure out how to update with a kit (can we compare values to stored kit?)
3. display switches on install that let users override defaults


Really, allowing #1 is plenty for the time being

**Comment by john-floren-gravwell** [comment] 2023-12-08 18:29
We now have a very crude updating process for kits. If we find a scheduled search with the same GUID, we overwrite it with the one that ships in the updated kit.

I could easily copy over some fields from the existing search, such as LastRun.

We can also bring over the BackfillEnabled from the existing version, although at that point we start to run into questions like "what happens if the old version of the kit set BackfillEnabled = false, and the new version has BackfillEnabled = true?"

We can implement backfilling from an initial start date by setting a field in the kit installation config, then using that to populate LastRun at install time. Ignore it for upgrades.

**Comment by ashnwade** [comment] 2023-12-08 21:52
updated by https://github.com/gravwell/backend/pull/1104

Closing in favor of streaming queries and proper aggs.
[mattermost discussion](https://mm.gravwell.io/gravwell/pl/kbaq8ecgk3dc78ruormjthu56r):
![Image](https://github.com/gravwell/gravwell/assets/107071905/cdfed8b0-9908-410b-9906-85bce3ae0d90)

**Closed by ashnwade** 2023-12-08 21:52 UTC
Labels: feature, customer request, High
